### PR TITLE
removed bigpicture tag from head section

### PR DESCRIPTION
**Pull request by altsang**
@XVincentX , i'm removing the tag here and will add via GTM so that we limit was is put out of band

### CODE REVIEW

**Comment by XVincentX** [comment]
I won't complain for this :trollface:

**Comment by altsang** [comment]
thx - can you publish ASAP, so that i can work with Jimmy to make sure all is working still? thx

**Comment by XVincentX** [comment]
That’s been published already. Power of automation.

**Comment by altsang** [comment]
👍

**Pull request merged**
