### PR TITLE
Add new icons

### LINKED ISSUE #173: docs:  update resource page with new icons for latest policies

### PR DESCRIPTION
**Pull request by XVincentX**
image

image

 Closes #173

### CODE REVIEW

**Comment by altsang** [comment]
per discussion in standup - think the new icons are proportionally and noticeably smaller than the existing - can we make larger somehow?

**Comment by XVincentX** [comment]
image
---------
image


@altsang Here it is now.

**Comment by XVincentX** [comment]
Connect #173 
Closes #173

**Comment by XVincentX** [comment]
@DrMegavolt See 2e9c909 for scopes documentation.

**Comment by altsang** [comment]
That looks a lot better - the order was changed though?

**Comment by XVincentX** [comment]
What order?

**Comment by altsang** [comment]
The authentication category and icons were first, is this an actual
screenshot of the page?

**Comment by XVincentX** [comment]
No, these are two different screenshots, I just pasted them in random order.

**Comment by altsang** [comment]
Ahh! Got it, 👍LGTM

**Comment by XVincentX** [comment]
@DrMegavolt On you for the scope docs.

**Review by DrMegavolt — APPROVED** [review]
LGTM

**Pull request merged**
