### PR TITLE
Add project roadmap on website

### LINKED ISSUE #236: Put RoadMap page on Express Gateway
and remove it from the wiki repository.

### PR DESCRIPTION
**Pull request by XVincentX**
Copy pasted from our wiki. Will modify that page once merged.

Connect #236 
Closes #236

### CODE REVIEW

**Review by altsang — COMMENTED** [review]
Do you think it might be better if the roadmap was top level - like in the resources section or even its own menu item?

**Comment by XVincentX** [comment]
Not really. 
Usually if I’m going to a project webspace I’m not really interested in what’s happening next for the project, but rather what it can do for me today.

The roadmap is something you look later, when you realize something is missing and — maybe it’s scheduled.

I might be wrong here — but this is my default behavior at least :)

**Comment by altsang** [comment]
Ok - I’m wondering about SEO value and google website parsing in its entry for us on a listing
We can put it there for now and move later

**Comment by XVincentX** [comment]
If Google crawler is respecting sitemap.xml file we should be set, because
we provide it.

I’m not an expert here though.

**Comment by altsang** [comment]
Would also say that in considering whether or not to use something - do they even have a roadmap in the first place

**Comment by altsang** [comment]
No I’m talking about a top level site section the way it does that is tries to discern your main nav from what I understand

**Comment by XVincentX** [comment]
I think we can achieve the same result by using some Google specific tags.  Can have a look into if you think it's worth the efforts. 

> Em 16 de mai de 2018, às 16:17, Al Tsang <notifications@github.com> escreveu:
> 
> No I’m talking about a top level site section the way it does that is tries to discern your main nav from what I understand 
>

**Comment by altsang** [comment]
Yes think it’s worth it, paying attention to details for SEO makes a difference long term, if we are moving this might as well address it now

**Comment by XVincentX** [comment]
> do they even have a roadmap in the first place

Not necessarily to be honest. If a project is fulfilling my use case, I do not care that much about further development. Also, tons of successful open source projects do not have a (public) roadmap

> Yes think it’s worth it

Sure. Do you want me to tackle this right now as part of this task or — merge this and iterate with a follow up PR?

**Comment by altsang** [comment]
Keep in mind we care about the enterprise consideration for a key piece of infrastructure, not just a npm module or otherwise fungible library, we can address in another story - can you please create story card, on plane thx!

**Comment by XVincentX** [comment]
Ok perfect.

**Pull request merged**
