### PR TITLE
Adding docs for eg gateway create.

### PR DESCRIPTION
**Pull request by kevinswiber**
Fixes ExpressGateway/express-gateway#319.

### CODE REVIEW

**Comment by DrMegavolt** [comment]
@kevinswiber you have gem file and _config committed. _config will break production I believe
@altsang please check the docs part

**Comment by kevinswiber** [comment]
Thanks, @DrMegavolt.  I keep accidentally typing `git commit -am` instead of `git commit -m`.  Grr.

**Comment by kevinswiber** [comment]
I added the Project Directory doc to this, as well, since it depends on `eg gateway create`.

**Comment by kevinswiber** [comment]
Fixes ExpressGateway/express-gateway#317.

**Pull request merged**
