### PR TITLE
 fix(docs): getting started 

### PR DESCRIPTION
**Pull request by gianpaj**
fix the output of curl when auth is enabled

and update output of `eg users create`

### CODE REVIEW

**Comment by XVincentX** [comment]
@gianpaj 

Thanks a lot for the contribution. I'm going to have a look to this as soon as possible.

In mean time, can I ask you to rebase the branch with the latest `dev`?

**Comment by gianpaj** [comment]
no problem @XVincentX 
i think i did it rebase.

feel free to squash the commits when you're merging 🙃

**Comment by gianpaj** [comment]
btw the issue with the build is in file:
https://github.com/ExpressGateway/express-gateway.io/blob/dev/_posts/2017-11-24-express-gateway-release-1-4-0.md

https://www.npmjs.com/package/express-gateway
->
https://www.npmjs.com/packages/express-gateway

other files have this link

**Comment by XVincentX** [comment]
Thanks a lot for this!

**Pull request merged**
