### PR TITLE
added Coozzy AG case study

### PR DESCRIPTION
**Pull request by altsang**
need logo help

### CODE REVIEW

**Comment by XVincentX** [comment]
@altsang Do you have a logo proposal?

**Comment by altsang** [comment]
there is a verticalized one they have that i need help resizing/cropping etc -

**Comment by XVincentX** [comment]
Are you going to take care of that? I can try, although I am a very bad Photoshop man.

V.

**Comment by altsang** [comment]
was going to ask for designer’s help, i tried and can’t do it

**Pull request closed without merging**
